# -*- coding: utf-8 -*-
#
# Galley documentation build configuration file, created by
# sphinx-quickstart on Sat Jul 27 14:58:42 2013.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os  # noqa: F401
import sys  # noqa: F401

import galley

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))  # noqa: E265

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'  # noqa: E265

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'  # noqa: E265

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Galley'
copyright = '2013, Russell Keith-Magee'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '.'.join(str(num) for num in galley.NUM_VERSION[:3] if isinstance(num, int))
# The full version, including alpha/beta/rc tags.
release = galley.VERSION

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None  # noqa: E265

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''  # noqa: E265
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'  # noqa: E265

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None  # noqa: E265

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True  # noqa: E265

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True  # noqa: E265

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False  # noqa: E265

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []  # noqa: E265


# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'default'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}  # noqa: E265

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []  # noqa: E265

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None  # noqa: E265

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None  # noqa: E265

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None  # noqa: E265

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#html_favicon = None  # noqa: E265

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'  # noqa: E265

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True  # noqa: E265

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}  # noqa: E265

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}  # noqa: E265

# If false, no module index is generated.
#html_domain_indices = True  # noqa: E265

# If false, no index is generated.
#html_use_index = True  # noqa: E265

# If true, the index is split into individual pages for each letter.
#html_split_index = False  # noqa: E265

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True  # noqa: E265

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True  # noqa: E265

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True  # noqa: E265

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''  # noqa: E265

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None  # noqa: E265

# Output file base name for HTML help builder.
htmlhelp_basename = 'galleydoc'


# -- Options for LaTeX output --------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',  # noqa: E265

    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',  # noqa: E265

    # Additional stuff for the LaTeX preamble.
    #'preamble': '',  # noqa: E265
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'galley.tex', 'Galley Documentation',
   'Russell Keith-Magee', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None  # noqa: E265

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False  # noqa: E265

# If true, show page references after internal links.
#latex_show_pagerefs = False  # noqa: E265

# If true, show URL addresses after external links.
#latex_show_urls = False  # noqa: E265

# Documents to append as an appendix to all manuals.
#latex_appendices = []  # noqa: E265

# If false, no module index is generated.
#latex_domain_indices = True  # noqa: E265


# -- Options for manual page output --------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'galley', 'Galley Documentation',
     ['Russell Keith-Magee'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False  # noqa: E265


# -- Options for Texinfo output ------------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'galley', 'Galley Documentation',
   'Russell Keith-Magee', 'Galley', 'GUI tool to assist in drafting documentation.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []  # noqa: E265

# If false, no module index is generated.
#texinfo_domain_indices = True  # noqa: E265

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'  # noqa: E265
